environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
cache:
  - node_modules
install:
  # Install the Redis
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  # Get the required Node version
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run-script test

# Set build version format here instead of in the admin panel.
version: "{build}"
